<#-- README Generator Template -->

# ${projectName}

${projectDescription}

---

## 🔧 Tech Stack

| Category      | Value                 |
|---------------|-----------------------|
| **Framework** | ${framework}          |
| **Language**  | ${language}           |
| **Build Tool**| ${buildTool}         |
| **Java**      | ${javaVersion}        |
| **Spring Boot** | ${springBootVersion} |

---

## 📦 Coordinates

| Key           | Value        |
|---------------|--------------|
| `groupId`     | `${groupId}` |
| `artifactId`  | `${artifactId}` |
| `package`     | `${packageName}` |

---

## 🚀 Quick Start

```bash
./mvnw clean package     # Build (using wrapper)
./mvnw spring-boot:run   # Run the application
```

> If Maven is installed globally, you may also use `mvn` instead of `./mvnw`.

<#-- Auto-config hints based on selected dependencies -->
<#if (hasH2!false) || (hasActuator!false) || (hasSecurity!false)>

    ---

    ## ⚙️ Auto Configuration Notes

    <#if hasH2!false>
        ### H2 (for JPA)
        This project includes an **in-memory H2 database** configuration because `spring-boot-starter-data-jpa` was selected.

        - JDBC URL: `jdbc:h2:mem:${artifactId}`
        - Console: `/h2-console` (if enabled)

    </#if>

    <#if hasActuator!false>
        ### Actuator
        Basic actuator exposure is enabled:

        - `/actuator/health`
        - `/actuator/info`

    </#if>

    <#if hasSecurity!false>
        ### Security
        `spring-boot-starter-security` is included. Endpoints may require authentication depending on defaults and your configuration.
    </#if>

</#if>

---

## 📁 Project Layout

```text
src
├─ main
│  ├─ java/${packageName?replace('.', '/')}
│  └─ resources/
└─ test
└─ java/${packageName?replace('.', '/')}
```

---

## 🧩 Layout Semantics

| Layout | Description |
|-------|-------------|
| `standard` | Layered packages: `controller`, `service`, `repository`, `domain`, `config` |
| `hexagonal` | Ports & Adapters structure: `domain`, `application`, `adapter`, `bootstrap` |

> The selected layout defines both the **package structure** and the **architecture governance level** applied to the project.

---

<#-- Optional hexagonal showcase -->
<#if hasHexSample?? && hasHexSample>
    ---

    ## 🧱 Hexagonal Architecture Example

    This project was generated with the optional **hexagonal layout**:

    ```bash
    --layout hexagonal
    ```

    With this flag, your `src/main/java/${packageName?replace('.', '/')}` tree is structured for:

    * `domain` – core business rules (no Spring dependencies)
    * `application` – use cases orchestrating ports
    * `adapter` – inbound & outbound adapters
    * `bootstrap` – configuration and wiring

    If you also enabled **sample code**:

    ```bash
    --sample-code basic
    ```

    then the project includes a minimal but complete **greeting flow** wired end-to-end:

    * **Domain & ports** – greeting model and port contracts
    * **Application** – greeting use case orchestration
    * **REST adapter** – sample controller exposing:

    ```bash
    GET /api/v1/sample/greetings/default
    → 200 OK
    {
    "text": "Hello from hexagonal sample!"
    }
    ```

    You can use this sample in two ways:

    * As a **teaching reference** for hexagonal structure in this codebase
    * As a **starting slice** to evolve into your real business modules

</#if>

---

## 📚 Selected Dependencies

<#if dependencies?has_content>
    | Dependency | Scope |
    |-----------|-------|
    <#list dependencies as d>
        | `${d.groupId}:${d.artifactId}`<#if d.version?? && d.version?has_content>:`${d.version}`</#if> | <#if d.scope?? && d.scope?has_content>${d.scope}<#else>default</#if> |
    </#list>
<#else>
    > No additional dependencies were selected.
</#if>

---

## 🧩 Next Steps

* ✔ Structure your domain and use case logic
* ✔ Add CI/CD pipelines or Docker support
* ✔ Configure profiles in `application.yml`
* ✔ Add more Spring Boot starters if needed

---

🏗 Generated by **Blueprint Platform — Codegen Blueprint CLI**
