# Codegen Spring Boot Initializr

A modern Spring Boot project initializer with **Hexagonal Architecture** baked in.
This tool generates a clean project scaffold you can extend — not just a blank template, but a foundation aligned with real-world best practices from companies like Netflix, Uber, Amazon, and Google.

---

## Features

* **Maven Wrapper & pom.xml** generated out of the box.
* **Hexagonal Architecture project layout** with `domain`, `application`, `adapter`, and `bootstrap` layers.
* **Artifacts** like `.gitignore`, `application.yml`, and optional `README.md` included.
* **Minimal Hexagonal Example**: a `Customer` aggregate with a single `CreateCustomer` use case, REST controller, and in-memory repository.
* **Extensible artifact generators**: each artifact is generated by its own adapter implementing the `ArtifactGenerator` contract.

---

## Generated Project Structure

```text
com.example.customer
├─ domain                         // Pure business rules, core domain logic
│  ├─ model                       // Aggregate root & value objects
│  │  ├─ Customer.java
│  │  └─ value
│  │     ├─ CustomerId.java
│  │     └─ Email.java
│  └─ port
│     └─ CustomerRepository.java  // Outbound port for persistence
│
├─ application                    // Use case orchestration
│  ├─ usecase
│  │  └─ customer
│  │     └─ create
│  │        ├─ CreateCustomerCommand.java
│  │        ├─ CreateCustomerResult.java
│  │        └─ CreateCustomerService.java
│  └─ mapper (optional)
│
├─ adapter                        // Technical implementations
│  ├─ inbound
│  │  └─ rest
│  │     └─ customer
│  │        ├─ CustomerController.java
│  │        └─ dto
│  │           ├─ CreateCustomerRequest.java
│  │           └─ CustomerResponse.java
│  └─ outbound
│     └─ persistence
│        └─ memory
│           └─ InMemoryCustomerRepository.java
│
└─ bootstrap                      // Spring configs, bean wiring
└─ SpringBeansConfig.java
```

---

## Why Only **Create**?

Instead of generating a full CRUD garden, the initializer provides a **minimal Create use case**:

* Keeps the scaffold **lean and comprehensible**.
* Shows the full flow across **all hexagonal layers**.
* Leaves room for you to extend with Update/Delete/Search as exercises.

---

## Artifact Generation Flow

Artifacts are produced by ordered generators implementing the `ArtifactGenerator` contract:

1. **MavenPomAdapter** → `pom.xml`
2. **GitIgnoreAdapter** → `.gitignore`
3. **ConfigFilesAdapter** → `application.yml`
4. **HexSourceScaffolderAdapter** → Java source files for domain/application/adapters
5. **HexTestScaffolderAdapter** → Minimal test scaffold
6. **ReadmeAdapter** → `README.md`
7. **MavenWrapperAdapter** → `.mvn/wrapper/maven-wrapper.properties`

Each adapter declares:

* `supports(ProjectBlueprint)` → whether to apply for a given template kind.
* `order()` → ensures proper generation sequence.
* `generateFiles(ProjectBlueprint)` → returns one or more `GeneratedFile` objects.

---

## Running the Generated Project

1. Extract the archive: `unzip myapp.zip`
2. Navigate: `cd myapp`
3. Build with Maven (if installed): `mvn package`
4. Or use the wrapper (no Maven required):

* Linux/macOS: `./mvnw package`
* Windows: `mvnw.cmd package`

---

## Example Use Case Flow

1. **POST /customers** with JSON body → handled by `CustomerController`.
2. Controller maps request → `CreateCustomerCommand`.
3. `CreateCustomerService` executes business logic → calls `CustomerRepository` port.
4. `InMemoryCustomerRepository` adapter persists entity → returns result.
5. Response mapped back to `CustomerResponse` and returned with `201 Created`.

---

## Philosophy

* **Domain first** → business rules and entities stay free of frameworks.
* **Ports define needs, not implementations** → adapters can change without touching domain/application.
* **Minimal, extendable** → enough to show the pattern, small enough to adapt.

---

## Next Steps

* Add your own use cases: Update, Delete, Search.
* Swap `InMemoryCustomerRepository` with a JPA or MongoDB adapter.
* Extend inbound side with CLI or messaging adapters.

---

## License

MIT License — see [LICENSE](LICENSE).
