<#-- README Generator Template -->

# ${projectName}

${projectDescription}

---

## 🔧 Tech Stack

| Category | Value |
|---------|------|
| **Framework** | ${framework} |
| **Language** | ${language} |
| **Build Tool** | ${buildTool?upper_case} |
| **Java** | ${javaVersion} |
| **Spring Boot** | ${springBootVersion} |

---

## 📦 Coordinates

| Key | Value |
|-----|------|
| `groupId` | `${groupId}` |
| `artifactId` | `${artifactId}` |
| `package` | `${packageName}` |

---

## 🚀 Quick Start

```bash
./mvnw clean package     # Build (using wrapper)
./mvnw spring-boot:run   # Run the application
```

> If Maven is installed globally, you may also use `mvn` instead of `./mvnw`.

---

## 📁 Project Layout

```
src
├─ main
│  ├─ java/${packageName?replace('.', '/')}
│  └─ resources/
└─ test
└─ java/${packageName?replace('.', '/')}
```

<#-- Optional hexagonal showcase -->
<#if hasHexSample?? && hasHexSample>

---

## 🧱 Hexagonal Architecture Example

This project includes an example **domain → application → adapter** structure:
* Domain models and rules
* Application use cases
* CLI / Web / Persistence adapters

Modular & clean expansion ready! ✨
</#if>

---

## 📚 Selected Dependencies

<#if dependencies?has_content>
    | Dependency | Scope |
    |-----------|-------|
    <#list dependencies as d>
        | `${d.groupId}:${d.artifactId}`<#if d.version?? && d.version?has_content>:`${d.version}`</#if> | <#if d.scope?? && d.scope?has_content>${d.scope}<#else>default</#if> |
    </#list>
<#else>
    > No additional dependencies were selected.
</#if>

---

## 🧩 Next Steps

✔ Structure your domain and use case logic
✔ Add CI/CD pipelines or Docker support
✔ Configure profiles in `application.yml`
✔ Add more Spring Boot starters if needed

---

🏗 Generated by **Blueprint Platform — Codegen Blueprint CLI**