coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "target/**"
  - "**/target/**"
  - "**/generated/**"
  - "**/generated-sources/**"

flags:
  codegen-blueprint:
    paths:
      - "src/main/java/"
      - "src/test/java/"